name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.*
  - seaborn=0.*
  - pandas=1.*
  - pip=20.*
  - pandas-profiling=2.11.*
  - pyarrow=2.*
  - wandb=0.*
  - ipywidgets=8.*
  - jinja2=3.0.3